#!/bin/sh

# By abxh (github)

tag="string:x-dunst-stack-tag:brightness"
icon="/usr/share/icons/Papirus-Dark/16x16/actions/brightnesssettings.svg"
path="/sys/class/backlight/amdgpu_bl1/"

raw_val=$(brightnessctl g)
min_val=0
max_val=$(brightnessctl m)

notify() {
	val=$((raw_val * 100 / 255))
	dunstify -h int:value:$val\
		 -h string:hlcolor:"#cad5ff"\
		 -h $tag\
		 -u low\
		 -i "$icon"\
		 "Brightness:"
}

case "$1" in
--inc|-i)
  brightnessctl s +5%
	notify
	;;
--dec|-d)
  brightnessctl s 5%-
	notify
	;;
--get|-g)
	echo $raw_val
	;;
*)
	echo "Usage: [SCRIPT] [COMMAND] [VALUE]"
	echo "Commands:"
	echo "  --inc/-i:			Increase brightness."
	echo "  --dec/-d:			Decrease brightness."
	echo "  --get/-g:			Get brightness by raw value."
	;;
esac
