live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#0B0A10"
foreground = "#E2E0EC"

[colors.normal]
black =   "#2B273F"
red =     "#E97193"
green =   "#AAC5A0"
yellow =  "#ECE0A8"
blue =    "#A8C5E6"
magenta = "#DFA7E7"
cyan =    "#A8E5E6"
white =   "#E2E0EC"

[colors.bright]
black =   "#61588E"
red =     "#E97193"
green =   "#AAC5A0"
yellow =  "#ECE0A8"
blue =    "#A8C5E6"
magenta = "#DFA7E7"
cyan =    "#A8E5E6"
white =   "#E2E0EC"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[font]
size = 12

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono NF"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono NF"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.85

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 20
y = 20
